{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: inference in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (0.9.15)\n",
      "Requirement already satisfied: APScheduler<=3.10.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (3.10.1)\n",
      "Requirement already satisfied: cython<=3.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (3.0.0)\n",
      "Requirement already satisfied: python-dotenv<=2.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (1.0.1)\n",
      "Requirement already satisfied: fastapi<1.0,>=0.100 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (0.110.0)\n",
      "Requirement already satisfied: numpy<=1.25.2 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (1.25.2)\n",
      "Requirement already satisfied: opencv-python<=4.8.0.76 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (4.8.0.76)\n",
      "Requirement already satisfied: piexif<=1.1.3 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (1.1.3)\n",
      "Requirement already satisfied: pillow<11.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (10.2.0)\n",
      "Requirement already satisfied: prometheus-fastapi-instrumentator<=6.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (6.0.0)\n",
      "Requirement already satisfied: redis<6.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (5.0.2)\n",
      "Requirement already satisfied: requests>=2.26.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (2.31.0)\n",
      "Requirement already satisfied: rich<=13.5.2 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (13.5.2)\n",
      "Requirement already satisfied: shapely<=2.0.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (2.0.1)\n",
      "Requirement already satisfied: supervision<1.0.0,>0.16.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (0.18.0)\n",
      "Requirement already satisfied: pybase64<2.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (1.3.2)\n",
      "Requirement already satisfied: scikit-image>=0.19.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (0.22.0)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (1.0.0)\n",
      "Requirement already satisfied: wheel>=0.38.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (0.42.0)\n",
      "Requirement already satisfied: setuptools>=65.5.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (69.1.1)\n",
      "Requirement already satisfied: pytest-asyncio<=0.21.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (0.21.1)\n",
      "Requirement already satisfied: networkx>=3.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (3.2.1)\n",
      "Requirement already satisfied: pydantic>=2.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (2.6.3)\n",
      "Requirement already satisfied: openai>=1.12.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (1.13.3)\n",
      "Requirement already satisfied: structlog>=24.1.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (24.1.0)\n",
      "Requirement already satisfied: onnxruntime<=1.15.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (1.15.1)\n",
      "Requirement already satisfied: GPUtil==1.4.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (1.4.0)\n",
      "Requirement already satisfied: inference-cli==0.9.15 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference) (0.9.15)\n",
      "Requirement already satisfied: docker==6.1.3 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-cli==0.9.15->inference) (6.1.3)\n",
      "Requirement already satisfied: typer==0.9.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-cli==0.9.15->inference) (0.9.0)\n",
      "Requirement already satisfied: skypilot==0.4.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-cli==0.9.15->inference) (0.4.1)\n",
      "Requirement already satisfied: inference-sdk>=0.9.8 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-cli==0.9.15->inference) (0.9.15)\n",
      "Requirement already satisfied: PyYAML>=6.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-cli==0.9.15->inference) (6.0.1)\n",
      "Requirement already satisfied: tqdm>=4.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-cli==0.9.15->inference) (4.66.2)\n",
      "Requirement already satisfied: py-cpuinfo>=9.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-cli==0.9.15->inference) (9.0.0)\n",
      "Requirement already satisfied: packaging>=14.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from docker==6.1.3->inference-cli==0.9.15->inference) (23.2)\n",
      "Requirement already satisfied: urllib3>=1.26.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from docker==6.1.3->inference-cli==0.9.15->inference) (1.26.18)\n",
      "Requirement already satisfied: websocket-client>=0.32.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from docker==6.1.3->inference-cli==0.9.15->inference) (1.7.0)\n",
      "Requirement already satisfied: cachetools in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (5.3.3)\n",
      "Requirement already satisfied: click>=7.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (8.1.7)\n",
      "Requirement already satisfied: colorama<0.4.5 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (0.4.4)\n",
      "Requirement already satisfied: cryptography in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (42.0.5)\n",
      "Requirement already satisfied: jinja2>=3.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (3.1.3)\n",
      "Requirement already satisfied: jsonschema in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (4.21.1)\n",
      "Requirement already satisfied: pandas>=1.3.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (2.2.1)\n",
      "Requirement already satisfied: pendulum in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (3.0.0)\n",
      "Requirement already satisfied: PrettyTable>=2.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (3.10.0)\n",
      "Requirement already satisfied: tabulate in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (0.9.0)\n",
      "Requirement already satisfied: typing-extensions in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (4.10.0)\n",
      "Requirement already satisfied: filelock>=3.6.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (3.13.1)\n",
      "Requirement already satisfied: psutil in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (5.9.8)\n",
      "Requirement already satisfied: pulp in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (2.8.0)\n",
      "Requirement already satisfied: awscli>=1.27.10 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (1.32.56)\n",
      "Requirement already satisfied: botocore>=1.29.10 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (1.34.56)\n",
      "Requirement already satisfied: boto3>=1.26.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from skypilot==0.4.1->inference-cli==0.9.15->inference) (1.34.56)\n",
      "Requirement already satisfied: six>=1.4.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from APScheduler<=3.10.1->inference) (1.16.0)\n",
      "Requirement already satisfied: pytz in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from APScheduler<=3.10.1->inference) (2024.1)\n",
      "Requirement already satisfied: tzlocal!=3.*,>=2.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from APScheduler<=3.10.1->inference) (5.2)\n",
      "Requirement already satisfied: starlette<0.37.0,>=0.36.3 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from fastapi<1.0,>=0.100->inference) (0.36.3)\n",
      "Requirement already satisfied: coloredlogs in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from onnxruntime<=1.15.1->inference) (15.0.1)\n",
      "Requirement already satisfied: flatbuffers in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from onnxruntime<=1.15.1->inference) (23.5.26)\n",
      "Requirement already satisfied: protobuf in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from onnxruntime<=1.15.1->inference) (4.25.3)\n",
      "Requirement already satisfied: sympy in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from onnxruntime<=1.15.1->inference) (1.12)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from openai>=1.12.0->inference) (4.3.0)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from openai>=1.12.0->inference) (1.9.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from openai>=1.12.0->inference) (0.27.0)\n",
      "Requirement already satisfied: sniffio in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from openai>=1.12.0->inference) (1.3.1)\n",
      "Requirement already satisfied: prometheus-client<1.0.0,>=0.8.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from prometheus-fastapi-instrumentator<=6.0.0->inference) (0.20.0)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from pydantic>=2.0->inference) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.16.3 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from pydantic>=2.0->inference) (2.16.3)\n",
      "Requirement already satisfied: pytest>=7.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from pytest-asyncio<=0.21.1->inference) (8.0.2)\n",
      "Requirement already satisfied: async-timeout>=4.0.3 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from redis<6.0.0->inference) (4.0.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from requests>=2.26.0->inference) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from requests>=2.26.0->inference) (2.10)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from requests>=2.26.0->inference) (2023.7.22)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from rich<=13.5.2->inference) (3.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from rich<=13.5.2->inference) (2.17.2)\n",
      "Requirement already satisfied: scipy>=1.8 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from scikit-image>=0.19.0->inference) (1.12.0)\n",
      "Requirement already satisfied: imageio>=2.27 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from scikit-image>=0.19.0->inference) (2.34.0)\n",
      "Requirement already satisfied: tifffile>=2022.8.12 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from scikit-image>=0.19.0->inference) (2024.2.12)\n",
      "Requirement already satisfied: lazy_loader>=0.3 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from scikit-image>=0.19.0->inference) (0.3)\n",
      "Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from supervision<1.0.0,>0.16.0->inference) (0.7.1)\n",
      "Requirement already satisfied: matplotlib>=3.6.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from supervision<1.0.0,>0.16.0->inference) (3.8.3)\n",
      "Requirement already satisfied: opencv-python-headless>=4.5.5.64 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from supervision<1.0.0,>0.16.0->inference) (4.8.0.74)\n",
      "Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from anyio<5,>=3.5.0->openai>=1.12.0->inference) (1.2.0)\n",
      "Requirement already satisfied: httpcore==1.* in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from httpx<1,>=0.23.0->openai>=1.12.0->inference) (1.0.4)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>=1.12.0->inference) (0.14.0)\n",
      "Requirement already satisfied: dataclasses-json>=0.6.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (0.6.4)\n",
      "Requirement already satisfied: aiohttp>=3.9.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (3.9.3)\n",
      "Requirement already satisfied: backoff>=2.2.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (2.2.1)\n",
      "Requirement already satisfied: aioresponses>=0.7.6 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (0.7.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich<=13.5.2->inference) (0.1.2)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<1.0.0,>0.16.0->inference) (1.2.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<1.0.0,>0.16.0->inference) (0.10.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<1.0.0,>0.16.0->inference) (4.49.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<1.0.0,>0.16.0->inference) (1.4.5)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<1.0.0,>0.16.0->inference) (3.1.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<1.0.0,>0.16.0->inference) (2.9.0.post0)\n",
      "Requirement already satisfied: iniconfig in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-asyncio<=0.21.1->inference) (2.0.0)\n",
      "Requirement already satisfied: pluggy<2.0,>=1.3.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-asyncio<=0.21.1->inference) (1.4.0)\n",
      "Requirement already satisfied: tomli>=1.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-asyncio<=0.21.1->inference) (2.0.1)\n",
      "Requirement already satisfied: humanfriendly>=9.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from coloredlogs->onnxruntime<=1.15.1->inference) (10.0)\n",
      "Requirement already satisfied: mpmath>=0.19 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from sympy->onnxruntime<=1.15.1->inference) (1.3.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from aiohttp>=3.9.0->inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from aiohttp>=3.9.0->inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (23.2.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from aiohttp>=3.9.0->inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (1.4.1)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from aiohttp>=3.9.0->inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (6.0.5)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from aiohttp>=3.9.0->inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (1.9.4)\n",
      "Requirement already satisfied: docutils<0.17,>=0.10 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from awscli>=1.27.10->skypilot==0.4.1->inference-cli==0.9.15->inference) (0.16)\n",
      "Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from awscli>=1.27.10->skypilot==0.4.1->inference-cli==0.9.15->inference) (0.10.0)\n",
      "Requirement already satisfied: rsa<4.8,>=3.1.2 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from awscli>=1.27.10->skypilot==0.4.1->inference-cli==0.9.15->inference) (4.7.2)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from botocore>=1.29.10->skypilot==0.4.1->inference-cli==0.9.15->inference) (1.0.1)\n",
      "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from dataclasses-json>=0.6.0->inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (3.21.1)\n",
      "Requirement already satisfied: typing-inspect<1,>=0.4.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from dataclasses-json>=0.6.0->inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (0.9.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from jinja2>=3.0->skypilot==0.4.1->inference-cli==0.9.15->inference) (2.1.5)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from pandas>=1.3.0->skypilot==0.4.1->inference-cli==0.9.15->inference) (2024.1)\n",
      "Requirement already satisfied: wcwidth in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from PrettyTable>=2.0.0->skypilot==0.4.1->inference-cli==0.9.15->inference) (0.2.13)\n",
      "Requirement already satisfied: cffi>=1.12 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from cryptography->skypilot==0.4.1->inference-cli==0.9.15->inference) (1.16.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from jsonschema->skypilot==0.4.1->inference-cli==0.9.15->inference) (2023.12.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from jsonschema->skypilot==0.4.1->inference-cli==0.9.15->inference) (0.33.0)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from jsonschema->skypilot==0.4.1->inference-cli==0.9.15->inference) (0.18.0)\n",
      "Requirement already satisfied: time-machine>=2.6.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from pendulum->skypilot==0.4.1->inference-cli==0.9.15->inference) (2.14.0)\n",
      "Requirement already satisfied: pycparser in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from cffi>=1.12->cryptography->skypilot==0.4.1->inference-cli==0.9.15->inference) (2.21)\n",
      "Requirement already satisfied: pyasn1>=0.1.3 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from rsa<4.8,>=3.1.2->awscli>=1.27.10->skypilot==0.4.1->inference-cli==0.9.15->inference) (0.5.1)\n",
      "Requirement already satisfied: mypy-extensions>=0.3.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json>=0.6.0->inference-sdk>=0.9.8->inference-cli==0.9.15->inference) (1.0.0)\n"
     ]
    }
   ],
   "source": [
    "! pip install inference"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from inference_sdk import InferenceHTTPClient\n",
    "from inference import get_model\n",
    "import supervision as sv\n",
    "import cv2 as cv\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: Roboflow in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (1.1.21)\n",
      "Requirement already satisfied: certifi==2023.7.22 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (2023.7.22)\n",
      "Requirement already satisfied: chardet==4.0.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (4.0.0)\n",
      "Requirement already satisfied: cycler==0.10.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (0.10.0)\n",
      "Requirement already satisfied: idna==2.10 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (2.10)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (1.4.5)\n",
      "Requirement already satisfied: matplotlib in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (3.8.3)\n",
      "Requirement already satisfied: numpy>=1.18.5 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (1.25.2)\n",
      "Requirement already satisfied: opencv-python-headless==4.8.0.74 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (4.8.0.74)\n",
      "Requirement already satisfied: Pillow>=7.1.2 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (10.2.0)\n",
      "Requirement already satisfied: python-dateutil in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (2.9.0.post0)\n",
      "Requirement already satisfied: python-dotenv in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (1.0.1)\n",
      "Requirement already satisfied: requests in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (2.31.0)\n",
      "Requirement already satisfied: six in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (1.16.0)\n",
      "Requirement already satisfied: supervision in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (0.18.0)\n",
      "Requirement already satisfied: urllib3>=1.26.6 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (1.26.18)\n",
      "Requirement already satisfied: tqdm>=4.41.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (4.66.2)\n",
      "Requirement already satisfied: PyYAML>=5.3.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (6.0.1)\n",
      "Requirement already satisfied: requests-toolbelt in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (1.0.0)\n",
      "Requirement already satisfied: python-magic in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from Roboflow) (0.4.27)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib->Roboflow) (1.2.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib->Roboflow) (4.49.0)\n",
      "Requirement already satisfied: packaging>=20.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib->Roboflow) (23.2)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from matplotlib->Roboflow) (3.1.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from requests->Roboflow) (3.3.2)\n",
      "Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from supervision->Roboflow) (0.7.1)\n",
      "Requirement already satisfied: scipy<2.0.0,>=1.10.0 in /Users/sarancibia/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages (from supervision->Roboflow) (1.12.0)\n"
     ]
    }
   ],
   "source": [
    "! pip install Roboflow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# initialize the client\n",
    "CLIENT = InferenceHTTPClient(\n",
    "    api_url=\"http://detect.roboflow.com\",\n",
    "    api_key=\"JVuvSUZ2T8BQEtoGVvtv\"\n",
    ")\n",
    "# infer on a local image\n",
    "\n",
    "result = CLIENT.infer(\"/Users/sarancibia/code/sarabarancibiag/Images-MOJI/00023.jpg\", model_id=\"manga-text-detection/2\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'time': 0.30261931100017136,\n",
       " 'image': {'width': 846, 'height': 1200},\n",
       " 'predictions': [{'x': 362.109375,\n",
       "   'y': 364.453125,\n",
       "   'width': 161.71875,\n",
       "   'height': 173.4375,\n",
       "   'confidence': 0.9801915884017944,\n",
       "   'class': 'text_bubble',\n",
       "   'class_id': 0,\n",
       "   'detection_id': '8ca74958-99c0-4769-a56a-049778c5d82c'},\n",
       "  {'x': 404.296875,\n",
       "   'y': 604.6875,\n",
       "   'width': 189.84375,\n",
       "   'height': 243.74999999999997,\n",
       "   'confidence': 0.9787070751190186,\n",
       "   'class': 'text_bubble',\n",
       "   'class_id': 0,\n",
       "   'detection_id': 'd60f682f-7df4-4237-a863-a54fe484b125'},\n",
       "  {'x': 386.71875,\n",
       "   'y': 858.3984375,\n",
       "   'width': 150.0,\n",
       "   'height': 169.921875,\n",
       "   'confidence': 0.9765786528587341,\n",
       "   'class': 'text_bubble',\n",
       "   'class_id': 0,\n",
       "   'detection_id': '04cc278f-ecaa-4770-b980-a237e0ad604a'},\n",
       "  {'x': 124.21874999999999,\n",
       "   'y': 1033.59375,\n",
       "   'width': 110.15625,\n",
       "   'height': 157.03125,\n",
       "   'confidence': 0.9744932055473328,\n",
       "   'class': 'text_bubble',\n",
       "   'class_id': 0,\n",
       "   'detection_id': 'd29f58f7-4429-413e-bf1d-76b220c213c0'},\n",
       "  {'x': 683.7890625,\n",
       "   'y': 856.0546875,\n",
       "   'width': 148.828125,\n",
       "   'height': 165.234375,\n",
       "   'confidence': 0.9686991572380066,\n",
       "   'class': 'text_bubble',\n",
       "   'class_id': 0,\n",
       "   'detection_id': '601b6ed5-dc3b-462b-822d-3e1c9cbf4777'},\n",
       "  {'x': 198.046875,\n",
       "   'y': 155.859375,\n",
       "   'width': 147.65625,\n",
       "   'height': 140.625,\n",
       "   'confidence': 0.9680235981941223,\n",
       "   'class': 'text_bubble',\n",
       "   'class_id': 0,\n",
       "   'detection_id': '93766724-ad3e-428b-a816-f8d1fb1dfc3d'},\n",
       "  {'x': 714.84375,\n",
       "   'y': 558.3984375,\n",
       "   'width': 147.65625,\n",
       "   'height': 214.453125,\n",
       "   'confidence': 0.9656388163566589,\n",
       "   'class': 'text_bubble',\n",
       "   'class_id': 0,\n",
       "   'detection_id': '4a110485-62bc-4536-a489-aec6baf1f251'},\n",
       "  {'x': 675.5859375,\n",
       "   'y': 128.90625,\n",
       "   'width': 162.890625,\n",
       "   'height': 206.25,\n",
       "   'confidence': 0.9631233215332031,\n",
       "   'class': 'text_bubble',\n",
       "   'class_id': 0,\n",
       "   'detection_id': 'f5d0cbc7-7f92-4239-8a78-603054a0210d'},\n",
       "  {'x': 111.91406249999999,\n",
       "   'y': 555.46875,\n",
       "   'width': 87.890625,\n",
       "   'height': 175.78125,\n",
       "   'confidence': 0.9497854113578796,\n",
       "   'class': 'text_bubble',\n",
       "   'class_id': 0,\n",
       "   'detection_id': '9a8cdc19-25f3-410d-af95-1f09a3f070a6'},\n",
       "  {'x': 738.8671875,\n",
       "   'y': 277.1484375,\n",
       "   'width': 36.328125,\n",
       "   'height': 78.515625,\n",
       "   'confidence': 0.4340708255767822,\n",
       "   'class': 'text_free',\n",
       "   'class_id': 1,\n",
       "   'detection_id': '529de536-0d27-4ef2-a907-387b117d6399'}]}"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "ename": "RoboflowAPINotAuthorizedError",
     "evalue": "Unauthorized access to roboflow API - check API key. Visit https://docs.roboflow.com/api-reference/authentication#retrieve-an-api-key to learn how to retrieve one.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mHTTPError\u001b[0m                                 Traceback (most recent call last)",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/inference/core/roboflow_api.py:78\u001b[0m, in \u001b[0;36mwrap_roboflow_api_errors.<locals>.decorator.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     77\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 78\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunction\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     79\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (requests\u001b[38;5;241m.\u001b[39mexceptions\u001b[38;5;241m.\u001b[39mConnectionError, \u001b[38;5;167;01mConnectionError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m error:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/inference/core/roboflow_api.py:198\u001b[0m, in \u001b[0;36mget_roboflow_model_data\u001b[0;34m(api_key, model_id, endpoint_type, device_id)\u001b[0m\n\u001b[1;32m    194\u001b[0m api_url \u001b[38;5;241m=\u001b[39m _add_params_to_url(\n\u001b[1;32m    195\u001b[0m     url\u001b[38;5;241m=\u001b[39m\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mAPI_BASE_URL\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m/\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mendpoint_type\u001b[38;5;241m.\u001b[39mvalue\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m/\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mmodel_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m    196\u001b[0m     params\u001b[38;5;241m=\u001b[39mparams,\n\u001b[1;32m    197\u001b[0m )\n\u001b[0;32m--> 198\u001b[0m api_data \u001b[38;5;241m=\u001b[39m \u001b[43m_get_from_url\u001b[49m\u001b[43m(\u001b[49m\u001b[43murl\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mapi_url\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    199\u001b[0m cache\u001b[38;5;241m.\u001b[39mset(\n\u001b[1;32m    200\u001b[0m     api_data_cache_key,\n\u001b[1;32m    201\u001b[0m     api_data,\n\u001b[1;32m    202\u001b[0m     expire\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m10\u001b[39m,\n\u001b[1;32m    203\u001b[0m )\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/inference/core/roboflow_api.py:355\u001b[0m, in \u001b[0;36m_get_from_url\u001b[0;34m(url, json_response)\u001b[0m\n\u001b[1;32m    354\u001b[0m response \u001b[38;5;241m=\u001b[39m requests\u001b[38;5;241m.\u001b[39mget(wrap_url(url))\n\u001b[0;32m--> 355\u001b[0m \u001b[43mapi_key_safe_raise_for_status\u001b[49m\u001b[43m(\u001b[49m\u001b[43mresponse\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mresponse\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    356\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m json_response:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/inference/core/utils/requests.py:15\u001b[0m, in \u001b[0;36mapi_key_safe_raise_for_status\u001b[0;34m(response)\u001b[0m\n\u001b[1;32m     14\u001b[0m response\u001b[38;5;241m.\u001b[39murl \u001b[38;5;241m=\u001b[39m API_KEY_PATTERN\u001b[38;5;241m.\u001b[39msub(deduct_api_key, response\u001b[38;5;241m.\u001b[39murl)\n\u001b[0;32m---> 15\u001b[0m \u001b[43mresponse\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mraise_for_status\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/requests/models.py:1021\u001b[0m, in \u001b[0;36mResponse.raise_for_status\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1020\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m http_error_msg:\n\u001b[0;32m-> 1021\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m HTTPError(http_error_msg, response\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m)\n",
      "\u001b[0;31mHTTPError\u001b[0m: 401 Client Error: Unauthorized for url: https://api.roboflow.com/ort/manga-text-detection/2?nocache=true&device=MacBook-Air-de-Sara.local&dynamic=true",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mRoboflowAPINotAuthorizedError\u001b[0m             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[7], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#Load model\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m model \u001b[38;5;241m=\u001b[39m \u001b[43mget_model\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmanga-text-detection/2\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/inference/models/utils.py:193\u001b[0m, in \u001b[0;36mget_model\u001b[0;34m(model_id, api_key, **kwargs)\u001b[0m\n\u001b[1;32m    192\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mget_model\u001b[39m(model_id, api_key\u001b[38;5;241m=\u001b[39mAPI_KEY, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[0;32m--> 193\u001b[0m     task, model \u001b[38;5;241m=\u001b[39m \u001b[43mget_model_type\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel_id\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mapi_key\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mapi_key\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    194\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m ROBOFLOW_MODEL_TYPES[(task, model)](model_id, api_key\u001b[38;5;241m=\u001b[39mapi_key, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/inference/core/registries/roboflow.py:113\u001b[0m, in \u001b[0;36mget_model_type\u001b[0;34m(model_id, api_key)\u001b[0m\n\u001b[1;32m    106\u001b[0m     save_model_metadata_in_cache(\n\u001b[1;32m    107\u001b[0m         dataset_id\u001b[38;5;241m=\u001b[39mdataset_id,\n\u001b[1;32m    108\u001b[0m         version_id\u001b[38;5;241m=\u001b[39mversion_id,\n\u001b[1;32m    109\u001b[0m         project_task_type\u001b[38;5;241m=\u001b[39mproject_task_type,\n\u001b[1;32m    110\u001b[0m         model_type\u001b[38;5;241m=\u001b[39mmodel_type,\n\u001b[1;32m    111\u001b[0m     )\n\u001b[1;32m    112\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m project_task_type, model_type\n\u001b[0;32m--> 113\u001b[0m api_data \u001b[38;5;241m=\u001b[39m \u001b[43mget_roboflow_model_data\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    114\u001b[0m \u001b[43m    \u001b[49m\u001b[43mapi_key\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mapi_key\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    115\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmodel_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmodel_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    116\u001b[0m \u001b[43m    \u001b[49m\u001b[43mendpoint_type\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mModelEndpointType\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mORT\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    117\u001b[0m \u001b[43m    \u001b[49m\u001b[43mdevice_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mGLOBAL_DEVICE_ID\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    118\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mort\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    119\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m api_data \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m ModelArtefactError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mError loading model artifacts from Roboflow API.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/inference/core/roboflow_api.py:91\u001b[0m, in \u001b[0;36mwrap_roboflow_api_errors.<locals>.decorator.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     89\u001b[0m     error_handler \u001b[38;5;241m=\u001b[39m user_handler_override\u001b[38;5;241m.\u001b[39mget(status_code, default_handler)\n\u001b[1;32m     90\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m error_handler \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m---> 91\u001b[0m         \u001b[43merror_handler\u001b[49m\u001b[43m(\u001b[49m\u001b[43merror\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     92\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m RoboflowAPIUnsuccessfulRequestError(\n\u001b[1;32m     93\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mUnsuccessful request to Roboflow API with response code: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mstatus_code\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m     94\u001b[0m     ) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01merror\u001b[39;00m\n\u001b[1;32m     95\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m requests\u001b[38;5;241m.\u001b[39mexceptions\u001b[38;5;241m.\u001b[39mInvalidJSONError \u001b[38;5;28;01mas\u001b[39;00m error:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/inference/core/roboflow_api.py:58\u001b[0m, in \u001b[0;36m<lambda>\u001b[0;34m(e)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mraise_from_lambda\u001b[39m(\n\u001b[1;32m     52\u001b[0m     inner_error: \u001b[38;5;167;01mException\u001b[39;00m, exception_type: Type[\u001b[38;5;167;01mException\u001b[39;00m], message: \u001b[38;5;28mstr\u001b[39m\n\u001b[1;32m     53\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m     54\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m exception_type(message) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01minner_error\u001b[39;00m\n\u001b[1;32m     57\u001b[0m DEFAULT_ERROR_HANDLERS \u001b[38;5;241m=\u001b[39m {\n\u001b[0;32m---> 58\u001b[0m     \u001b[38;5;241m401\u001b[39m: \u001b[38;5;28;01mlambda\u001b[39;00m e: \u001b[43mraise_from_lambda\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m     59\u001b[0m \u001b[43m        \u001b[49m\u001b[43me\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     60\u001b[0m \u001b[43m        \u001b[49m\u001b[43mRoboflowAPINotAuthorizedError\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     61\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mUnauthorized access to roboflow API - check API key. Visit \u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\n\u001b[1;32m     62\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mhttps://docs.roboflow.com/api-reference/authentication#retrieve-an-api-key to learn how to retrieve one.\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m     63\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m,\n\u001b[1;32m     64\u001b[0m     \u001b[38;5;241m404\u001b[39m: \u001b[38;5;28;01mlambda\u001b[39;00m e: raise_from_lambda(\n\u001b[1;32m     65\u001b[0m         e, RoboflowAPINotNotFoundError, NOT_FOUND_ERROR_MESSAGE\n\u001b[1;32m     66\u001b[0m     ),\n\u001b[1;32m     67\u001b[0m }\n\u001b[1;32m     70\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mwrap_roboflow_api_errors\u001b[39m(\n\u001b[1;32m     71\u001b[0m     http_errors_handlers: Optional[\n\u001b[1;32m     72\u001b[0m         Dict[\u001b[38;5;28mint\u001b[39m, Callable[[Union[requests\u001b[38;5;241m.\u001b[39mexceptions\u001b[38;5;241m.\u001b[39mHTTPError]], \u001b[38;5;28;01mNone\u001b[39;00m]]\n\u001b[1;32m     73\u001b[0m     ] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m     74\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mcallable\u001b[39m:\n\u001b[1;32m     75\u001b[0m     \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mdecorator\u001b[39m(function: \u001b[38;5;28mcallable\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mcallable\u001b[39m:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/moji/lib/python3.10/site-packages/inference/core/roboflow_api.py:54\u001b[0m, in \u001b[0;36mraise_from_lambda\u001b[0;34m(inner_error, exception_type, message)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mraise_from_lambda\u001b[39m(\n\u001b[1;32m     52\u001b[0m     inner_error: \u001b[38;5;167;01mException\u001b[39;00m, exception_type: Type[\u001b[38;5;167;01mException\u001b[39;00m], message: \u001b[38;5;28mstr\u001b[39m\n\u001b[1;32m     53\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m---> 54\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m exception_type(message) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01minner_error\u001b[39;00m\n",
      "\u001b[0;31mRoboflowAPINotAuthorizedError\u001b[0m: Unauthorized access to roboflow API - check API key. Visit https://docs.roboflow.com/api-reference/authentication#retrieve-an-api-key to learn how to retrieve one."
     ]
    }
   ],
   "source": [
    "#Load model\n",
    "model = get_model(model_id=\"manga-text-detection/2\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'Roboflow' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[10], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m rf \u001b[38;5;241m=\u001b[39m \u001b[43mRoboflow\u001b[49m(api_key\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mJVuvSUZ2T8BQEtoGVvtv\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m      2\u001b[0m project \u001b[38;5;241m=\u001b[39m rf\u001b[38;5;241m.\u001b[39mworkspace()\u001b[38;5;241m.\u001b[39mproject(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmanga-text-detection\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m      3\u001b[0m model \u001b[38;5;241m=\u001b[39m project\u001b[38;5;241m.\u001b[39mversion(\u001b[38;5;241m2\u001b[39m)\u001b[38;5;241m.\u001b[39mmodel\n",
      "\u001b[0;31mNameError\u001b[0m: name 'Roboflow' is not defined"
     ]
    }
   ],
   "source": [
    "rf = Roboflow(api_key=\"JVuvSUZ2T8BQEtoGVvtv\")\n",
    "project = rf.workspace().project(\"manga-text-detection\")\n",
    "model = project.version(2).model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "#Run inference\n",
    "results = model.infer(image)\n",
    "\n",
    "#Load results into Supervision Detection API\n",
    "detections = sv.Detections.from_inference(\n",
    "    results[0].dict(by_alias=True, exclude_none=True)\n",
    ")\n",
    "\n",
    "#Create Supervision annotators\n",
    "bounding_box_annotator = sv.BoundingBoxAnnotator()\n",
    "label_annotator = sv.LabelAnnotator()\n",
    "\n",
    "#Extract labels array from inference results\n",
    "labels = [p.class_name for p in results[0].predictions]\n",
    "\n",
    "\n",
    "\n",
    "#Apply results to image using Supervision annotators\n",
    "annotated_image = bounding_box_annotator.annotate(scene=image, detections=detections)\n",
    "annotated_image = label_annotator.annotate(\n",
    "    scene=annotated_image, detections=detections, labels=labels\n",
    ")\n",
    "\n",
    "#Write annotated image to file or display image\n",
    "cv2.imwrite(\"00023.jpg\", annotated_image)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "moji",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
